Biblioteca/Biblioteca/urls.py
from django.urls import include
from django.contrib import admin
from django.urls import path
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
#TODO: Verificar el proceso de reestablecimiento de contraseña
#TODO: Checar si se puede modificar el nombre de el url de la app de cuenta de django de accounts a cuentas
#TODO: Usar formularios de bootstrap para formulario de inicio de sesion
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='catalogo/', permanent=True)),
    path('catalogo/', include('catalogo.urls')),
    path('cuentas/', include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Biblioteca/catalogo/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('libros/', views.ListaLibros.as_view(), name='libros'),
    path('libros/<int:pk>/', views.DetalleLibro.as_view(), name='detalle-libro'),
    path('libros/crear/', views.CrearLibro.as_view(), name='crear-libro'),
    path('libros/<uuid:pk>/actualizar/', views.ActualizarLibro.as_view(), name='actualizar-libro'),
    path('libros/<uuid:pk>/eliminar/', views.EliminarLibro.as_view(), name='eliminar-libro'),
    path('autores/', views.ListaAutores.as_view(), name='autores'),
    path('autores/<int:pk>/', views.DetalleAutor.as_view(), name='detalle-autor'),
    path('mislibros/', views.ListaLibrosPrestatario.as_view(), name='mis-prestamos'),
    path('prestados/', views.ListaLibrosPrestados.as_view(), name='todos-prestamos'),
    path('libros/<uuid:pk>/renovar', views.renovar_libro_bibliotecario, name='renovar-libro-bibliotecario'),
    path('disponibles/', views.consulta_libros_disponibles, name='libros-disponibles'),
    path('libros/<int:pk>/cambiar-imagen', views.CambiarImagenLibro.as_view(), name='cambiar-imagen-libro'),
    path('correo/', views.mandar_correo, name='correo'),
]

Biblioteca/catalogo/models.py
import safedelete.models
from django.db import models
from django.urls import reverse
import uuid
from django.contrib.auth.models import User
from datetime import date
from safedelete.models import SafeDeleteModel

#TODO: Arreglar el bug donde la instancia de libro no deja eliminar el libro aunque se encuentre la instanca eliminada

class Timestamp(models.Model):
    """Un modelo abstracto el cual contiene los campos de fecha de creacion y actualizacion"""
    creado_en = models.DateTimeField(auto_now_add=True)
    editado_en = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

class Autor(SafeDeleteModel, Timestamp):
    """Model representing an author."""

    primer_nombre = models.CharField(max_length=100)
    apellido = models.CharField(max_length=100)
    fecha_nacimiento = models.DateField(null=True, blank=True)
    fecha_defuncion = models.DateField('Murió', null=True, blank=True)

    class Meta:
        ordering = ['primer_nombre', 'apellido']

    def get_absolute_url(self):
        """Retorna el url para acceder al detalle del registro."""
        return reverse('detalle-autor', args=[str(self.id)])

    def __str__(self):
        """Cadena que representa al objeto."""
        return f'{self.apellido}, {self.primer_nombre}'

class Genero(SafeDeleteModel, Timestamp):
    """Un modelo que representa el género de un libro."""

    nombre = models.CharField(max_length=200, help_text='Inserta un género de libro (e.g. Ciencia Ficción)')

    def __str__(self):
        """Cadena que representa al modelo."""
        return self.nombre


class Libro(SafeDeleteModel, Timestamp):
    """Modelo que representa a un libro (pero no una copia específica)."""
    _safedelete_policy = safedelete.models.SOFT_DELETE_CASCADE

    titulo = models.CharField(max_length=200)
    autor = models.ForeignKey(Autor, on_delete=models.SET_NULL, null=True)
    resumen = models.TextField(max_length=1000, help_text='Inserta una breve descripción del libro')
    isbn = models.CharField('ISBN', max_length=13, unique=True,
                            help_text='13 caracteres <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>')
    genero = models.ManyToManyField(Genero, help_text='Selecciona uno o varios géneros para este libro')
    portada = models.ImageField(blank=True, null=True)

    def __str__(self):
        """Cadena que representa al modelo."""
        return self.titulo

    def get_absolute_url(self):
        """Retorna un url para acceder al detalle del registro."""
        return reverse('detalle-libro', args=[str(self.id)])


class InstanciaLibro(SafeDeleteModel, Timestamp):
    """Modelo que representa una copia específica de un libro (e.g. que puede ser prestado de la biblioteca)."""

    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
                          help_text='Identificador único para este libro particular en toda la biblioteca')
    libro = models.ForeignKey('Libro', on_delete=models.CASCADE, null=True)
    sello = models.CharField(max_length=200)
    fecha_entrega = models.DateField(null=True, blank=True)
    prestatario = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    ESTADO_PRESTAMO = (
        ('m', 'Mantenimiento'),
        ('p', 'En Prestamo'),
        ('d', 'Disponible'),
        ('r', 'Reservado'),
    )

    estado = models.CharField(
        max_length=1,
        choices=ESTADO_PRESTAMO,
        blank=True,
        default='m',
        help_text='Disponibilidad del libro',
    )

    # Nótese que es muy importante definir un ordenamiento para usar la función de book.bookinstance__set ya que el objeto de paginación lo necesita para saber que están en el orden correcto
    """
    Si no quieres definir ordenamiento en el modelo estas son las alternativas:

    Add a ordering inside a class Meta declaration on your model.
    Add a queryset attribute in your custom class-based view, specifying an order_by().
    Adding a get_queryset method to your custom class-based view and also specify the order_by().¿
    """

    class Meta:
        ordering = ['fecha_entrega']
        permissions = (("puede_marcar_retornado", "Marcar libro como retornado"),)

    def __str__(self):
        """Cadena que representa al modelo."""
        return f'{self.id} ({self.libro.titulo})'

    @property
    def esta_atrasado(self):
        if self.fecha_entrega and date.today() > self.fecha_entrega:
            return True
        return False

    def save(self, *args, **kwargs):
        """
        Función que usaremos como mutator para cambiar el formato de un campo al guardar.
        """
        self.sello = self.sello.title()
        super().save(*args, **kwargs)

Biblioteca/catalogo/forms.py
import datetime

from django import forms

from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from .models import InstanciaLibro

class FormularioRenovacionLibro(forms.Form):
    fecha_renovacion = forms.DateField(help_text="Ingrese una fecha entre ahora y 4 semanas (predeterminado 3).")

    def clean_fecha_renovacion(self):
        data = self.cleaned_data['fecha_renovacion']

        #Checamos que la fecha no sea anterior a la actual
        if data < datetime.date.today():
            raise ValidationError(_('Fecha inválida - renovación en el pasado'))

        #Checamos que la fecha no sea posterior a 4 semanas
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Fecha inválida - renovación con más de 4 semanas de antelación'))

        #Retornamos los datos limpios
        return data

"""Create a class to model a InstanciaLibro as a form"""
class FormularioCrearInstanciaLibro(forms.ModelForm):
    class Meta:
        model = InstanciaLibro
        fields = ['libro', 'sello']

class FormularioEditarInstanciaLibro(forms.ModelForm):
    class Meta:
        model = InstanciaLibro
        fields = ['libro', 'sello']

Biblioteca/catalogo/views.py
import datetime

from django.contrib.auth.decorators import login_required, permission_required
from django.core.mail import send_mail
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.http import JsonResponse
from django.views.generic.edit import CreateView, UpdateView, DeleteView
# Create your views here.
from .forms import FormularioRenovacionLibro, FormularioCrearInstanciaLibro, FormularioEditarInstanciaLibro
from .models import Libro, Autor, InstanciaLibro, Genero

# TODO: Checar si hay una manera de saber que un usuario pertenece a un grupo en vez de usar catalogo.puede_marcar_retornado

class CrearLibro(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    form_class = FormularioCrearInstanciaLibro
    permission_required = 'catalogo.add_instancialibro'
    template_name = 'crear_libro.html'

    def get_success_url(self):
        return reverse('detalle-libro', kwargs={'pk': self.object.libro.id})

    def form_valid(self, form):
        response = super().form_valid(form)
        self.object.fecha_entrega = datetime.date.today() + datetime.timedelta(weeks=3)
        self.object.save()
        return response

class ActualizarLibro(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = InstanciaLibro
    form_class = FormularioEditarInstanciaLibro
    permission_required = 'catalogo.change_instancialibro'
    template_name = 'actualizar_libro.html'

    def get_success_url(self):
        return reverse('detalle-libro', kwargs={'pk': self.object.libro.id})

class EliminarLibro(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = InstanciaLibro
    permission_required = 'catalogo.delete_instancialibro'
    template_name = 'eliminar_libro.html'

    def get_success_url(self):
        return reverse('detalle-libro', kwargs={'pk': self.object.libro.id})

def index(request):
    """Vista de página principal"""

    num_libros = Libro.objects.all().count()
    num_instancias = InstanciaLibro.objects.all().count()

    #Libros disponibles (status = 'a')
    num_instancias_disponibles = InstanciaLibro.objects.filter(estado__exact='d').count()

    num_autores = Autor.objects.count()

    context = {
        'num_libros': num_libros,
        'num_instancias': num_instancias,
        'num_instancias_disponibles': num_instancias_disponibles,
        'num_autores': num_autores,
    }

    # Render the HTML template index.html with the data in the context variable
    return render(request, 'index.html', context=context)

class ListaLibros(generic.ListView):
    model = Libro
    context_object_name = 'libros'
    template_name = 'lista_libros.html'

class DetalleLibro(generic.DetailView):
    model = Libro
    context_object_name = 'libro'
    template_name = 'detalle_libro.html'

class ListaAutores(generic.ListView):
    model = Autor
    context_object_name = 'autores'
    template_name = 'lista_autores.html'

class DetalleAutor(generic.DetailView):
    model = Autor
    context_object_name = 'autor'
    template_name = 'detalle_autor.html'

class ListaLibrosPrestatario(LoginRequiredMixin, generic.ListView):
    """Vista genérica basada en clases que enumera libros prestados al usuario actual."""
    model = InstanciaLibro
    context_object_name = 'libros'
    template_name = 'lista_libros_prestatario.html'

    def get_queryset(self):
        """Devuelve los libros prestados al usuario actual."""
        return InstanciaLibro.objects.filter(prestatario=self.request.user).order_by('fecha_entrega')

class ListaLibrosPrestados(PermissionRequiredMixin, generic.ListView):
    """Vista genérica basada en clases que enumera libros prestados en general."""
    model = InstanciaLibro
    permission_required = 'catalogo.puede_marcar_retornado'
    context_object_name = 'libros'
    template_name = 'lista_libros_prestados.html'

    def get_queryset(self):
        """Devuelve los libros prestados al usuario actual."""
        return InstanciaLibro.objects.filter(estado__exact='p').order_by('fecha_entrega')

@login_required
@permission_required('catalogo.puede_marcar_retornado', raise_exception=True)
def renovar_libro_bibliotecario(request, pk):
    """Vista para renovar un libro prestado por el usuario actual."""

    instancia = get_object_or_404(InstanciaLibro, pk=pk)
    if request.method == 'POST':
        formulario = FormularioRenovacionLibro(request.POST)
        if formulario.is_valid():
            instancia.fecha_entrega = formulario.cleaned_data['fecha_renovacion']
            instancia.save()

            return HttpResponseRedirect(reverse('todos-prestamos'))
        else:
            print(formulario.errors)
    else:
        fecha_propuesta = datetime.date.today() + datetime.timedelta(weeks=3)
        formulario = FormularioRenovacionLibro(initial={'fecha_renovacion': fecha_propuesta})

    context = {'formulario': formulario, 'instancia': instancia}
    return render(request, 'renovar_libro_bibliotecario.html', context)

def instancia_libro_to_dict(instancia):
    """Function to turn an InstanciaLibro object into a dictionary"""
    titulo = instancia.libro.titulo
    id = instancia.id

    return {'titulo': titulo,
            'id': id}

"""Function to turn a list of InstanciaLibro objects into a list of dictionaries"""

def consulta_libros_disponibles(request):
    """Vista para consultar libros disponibles."""

    libros = InstanciaLibro.objects.filter(estado__exact='d')
    libros_dict = [instancia_libro_to_dict(libro) for libro in libros]
    respuesta = {'libros': libros_dict}
    return JsonResponse(respuesta)

def mandar_correo(request):
    """Vista para mandar correos al usuario."""
    if request.user.is_authenticated:
        cantidad_libros = InstanciaLibro.objects.filter(prestatario=request.user).count()
        send_mail(
            f'Información de préstamo',
            f'Hola, {request.user.username}!\nQueremos recordarte que tienes {cantidad_libros} préstamo pendiente de entrega.',
            'emilio.nuno@alumnos.udg.mx',
            [f'{request.user.email}'],
            fail_silently=False,
        )
    return HttpResponseRedirect(reverse('index'))

class CambiarImagenLibro(LoginRequiredMixin, PermissionRequiredMixin, generic.UpdateView):
    """Vista para editar la imagen de un libro."""
    model = Libro
    fields = ['portada']
    permission_required = 'catalogo.puede_marcar_retornado.'
    template_name = 'editar_imagen_libro.html'

Biblioteca/catalogo/templates/actualizar_libro.html
{% extends "base.html" %}

{% block contenido %}
  <h1 class="text-center">Actualiza un libro</h1>

<!-- TODO: Checar si se puede ajustar base_formulario para incluir el contenedor flex dentro de este archivo -->
<div class="d-flex justify-content-center">
  {% if form.errors %}
    <div class="alert alert-danger">
      {{ form.errors }}
    </div>
  {% endif %}
    <form action="" method="post">
    {% csrf_token %}
    <div class="form-group">
      <div class="mb-2">
        {{ form.libro.label_tag  }}
        {{ form.libro }}
        </div>
    <div class="mb-2">
      {{ form.sello.label_tag  }}
        {{ form.sello }}
        </div>
      <button type="submit" class="btn btn-primary">Actualizar Libro</button>
    </div>
  </form>
</div>
{% endblock %}

Biblioteca/catalogo/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    {% block titulo %}<title>Biblioteca</title>{% endblock %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
</head>

<body>
<div class="container">
  {% block navegacion %}
    <!-- TODO: Agregar dropdown para autenticacion y para staff como en https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Forms/forms_example_create_book.png -->
    <!-- TODO: Eliminar los archivos estáticos -->
    <nav class="navbar navbar-light navbar-expand-md">
        <div class="container-fluid"><a class="navbar-brand" href="#">Biblioteca</a>
            <button data-bs-toggle="collapse" class="navbar-toggler" data-bs-target="#navcol-1"><span
                    class="visually-hidden">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navcol-1">
                <ul class="navbar-nav">
                    <li class="nav-item"><a class="nav-link active" href="{% url 'index' %}">Página Principal</a></li>
                    <li class="nav-item"><a class="nav-link active" href="{% url 'libros' %}">Todos los Libros</a></li>
                    <li class="nav-item"><a class="nav-link active" href="{% url 'autores' %}">Todos los Autores</a></li>
                    <li class="nav-item"><a class="nav-link active" href="{% url 'correo' %}">Mandar Correo</a></li>
                    {% if user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link active" href="{% url 'mis-prestamos' %}">Mis Préstamos</a></li>
                    <li class="nav-item"><a class="nav-link active" href="{% url 'logout' %}">Cerrar Sesión</a></li>
                    {% else %}
                    <li class="nav-item"><a class="nav-link active" href="{% url 'login' %}">Iniciar Sesión</a></li>
                    {% endif %}
                    {% if perms.catalogo.puede_marcar_retornado %}
                    <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Staff
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <a class="dropdown-item" href="{% url 'todos-prestamos' %}">Todos los Préstamos</a>
                      <a class="dropdown-item" href="{% url 'crear-libro' %}">Agregar Libro</a>
                    </div>
                  </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
  {% endblock %}
  {% block contenido %}
  {% endblock %}
</div>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
</body>

</html>

Biblioteca/catalogo/templates/base_formulario.html
<div class="d-flex justify-content-center">
    {% block contenido_formulario %}
    {% endblock %}
</div>

Biblioteca/catalogo/templates/crear_libro.html
{% extends "base.html" %}

{% block contenido %}
  <h1 class="text-center">Da de alta un nuevo libro</h1>

<!-- TODO: Checar si se puede ajustar base_formulario para incluir el contenedor flex dentro de este archivo -->
<div class="d-flex justify-content-center">
  {% if form.errors %}
    <div class="alert alert-danger">
      {{ form.errors }}
    </div>
  {% endif %}
    <form action="" method="post">
    {% csrf_token %}
    <div class="form-group">
      <div class="mb-2">
        {{ form.libro.label_tag  }}
        {{ form.libro }}
        </div>
    <div class="mb-2">
      {{ form.sello.label_tag  }}
        {{ form.sello }}
        </div>
      <button type="submit" class="btn btn-primary">Crear Libro</button>
    </div>
  </form>
</div>
{% endblock %}

Biblioteca/catalogo/templates/detalle_autor.html
{% extends "base.html" %}

{% block contenido %}
<h1>Autor: {{ autor }} </h1>
<p>{{autor.fecha_nacimiento}} - {% if autor.fecha_defuncion %}{{autor.fecha_defuncion}}{% endif %}</p>

<div style="margin-left:20px;margin-top:20px">
<h4>Libros</h4>

<dl>
{% for libro in autor.libro_set.all %}
  <dt><a href="{{ libro.get_absolute_url }}">{{libro}}</a> ({{libro.instancialibro_set.all.count}})</dt>
  <dd>{{libro.resumen}}</dd>
{% endfor %}
</dl>

</div>
{% endblock %}

Biblioteca/catalogo/templates/detalle_libro.html
{% extends "base.html" %}
{% load static %}

{% block contenido %}
<h1>Titulo: {{ libro.titulo }}</h1>
<p><strong>Autor:</strong> <a href="{{ libro.autor.get_absolute_url }}">{{ libro.autor }}</a></p>
{% if not libro.portada %}
<img src="{% static '/portadas/no-disponible.png' %}" alt="Portada del Libro">
{% else %}
<img src="{{ libro.portada.url }}" alt="Portada del Libro">
{% endif %}
<a href="{% url 'cambiar-imagen-libro' libro.id %}">Editar Foto</a>
<p><strong>Resumen:</strong> {{ libro.resumen }}</p>
<p><strong>ISBN:</strong> {{ libro.isbn }}</p>
<p><strong>Género:</strong> {{ libro.genero.all|join:", " }}</p>

<div style="margin-left:20px;margin-top:20px">
    <h4>Copias</h4>

    {% for copia in libro.instancialibro_set.all %}
    <hr>
    <p class="{% if copia.estado == 'd' %}text-success{% elif copia.estado == 'm' %}text-danger{% else %}text-warning{% endif %}">
        {{ copia.get_estado_display }}
    </p>
    {% if copia.estado != 'd' %}
    <p><strong>Retornar en:</strong> {{ copia.fecha_entrega }}</p>
    {% endif %}
    <p><strong>Sello:</strong> {{ copia.sello }}</p>
    <p class="text-muted"><strong>Id:</strong> {{ copia.id }}</p>
    {% if perms.catalogo.puede_marcar_retornado %}
    <a href="{% url 'actualizar-libro' copia.id %}">Actualizar</a>
    <div class="vr"></div>
    {% endif %}
    {% if perms.catalogo.puede_marcar_retornado %}
    <a href="{% url 'eliminar-libro' copia.id %}">Eliminar</a>
    {% endif %}
    {% endfor %}
</div>
{% endblock %}

Biblioteca/catalogo/templates/editar_imagen_libro.html
{% extends "base.html" %}

{% block contenido %}
  <h1 class="text-center">Actualiza la Imagen del Libro: {{ libro.titulo }}</h1>

<!-- TODO: Checar si se puede ajustar base_formulario para incluir el contenedor flex dentro de este archivo -->
<div class="d-flex justify-content-center">
  {% if form.errors %}
    <div class="alert alert-danger">
      {{ form.errors }}
    </div>
  {% endif %}
    <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group">
      <div class="mb-1">
        {{ form.portada.label_tag  }}
        {{ form.portada }}
      </div>
      <button type="submit" class="btn btn-primary">Actualizar Libro</button>
    </div>
  </form>
</div>
{% endblock %}

Biblioteca/catalogo/templates/eliminar_libro.html
{% extends "base.html" %}

{% block contenido %}
  <h1 class="text-center">¿Seguro que quieres eliminar este libro?</h1>

<!-- TODO: Checar si se puede ajustar base_formulario para incluir el contenedor flex dentro de este archivo -->
<div class="d-flex justify-content-center">
  {% if form.errors %}
    <div class="alert alert-danger">
      {{ form.errors }}
    </div>
  {% endif %}
    <form action="" method="post">
    {% csrf_token %}
    <div class="form-group">
      <div class="mb-2">
        {{ form.libro.label_tag  }}
        {{ form.libro }}
        </div>
    <div class="mb-2">
      {{ form.sello.label_tag  }}
        {{ form.sello }}
        </div>
      <button type="submit" class="btn btn-danger">Quiero eliminar este libro</button>
    </div>
  </form>
</div>
{% endblock %}

Biblioteca/catalogo/templates/index.html
{% extends 'base.html' %}
{% block contenido %}
<div class="text-center">
        <h1>Página Principal de la Biblioteca</h1>
        {% if user.is_authenticated %}
            <p>Bienvenido a la aplicación web de la biblioteca desarrollada por Emilio, {{ user.username }}<br></p>
        {% else %}
            <p>Bienvenido a la aplicación web de la biblioteca, invitado<br></p>
        {% endif %}
        <p>Se encuentran los siguientes registros en la base de datos:</p>
    </div>
    <div class="d-flex justify-content-center">
        <ul>
            <li>Libros: {{ num_libros }}</li>
            <li>Copias: {{ num_instancias }}</li>
            <li>Copias disponibles: {{ num_instancias_disponibles }}</li>
            <li>Autores: {{ num_autores }}</li>
        </ul>
    </div>
{% endblock %}

Biblioteca/catalogo/templates/lista_autores.html
{% extends "base.html" %}

{% block contenido %}
<h1>Lista de Autores</h1>

{% if autores %}
  <ul>

  {% for autor in autores %}
    <li>
      <a href="{{ autor.get_absolute_url }}">
      {{ autor }} ({{autor.fecha_nacimiento}} - {% if autor.fecha_defuncion %}{{autor.fecha_defuncion}}{% endif %})
      </a>
    </li>
  {% endfor %}

 </ul>
{% else %}
  <p>No hay autores disponibles.</p>
{% endif %}
        
        
        
{% endblock %}

Biblioteca/catalogo/templates/lista_libros.html
{% extends "base.html" %}

{% block contenido %}
  <h1>Lista de Libros</h1>
  {% if libros %}
  <ul>
    {% for libro in libros %}
      <li>
        <a href="{{ libro.get_absolute_url }}">{{ libro.titulo }}</a> ({{libro.autor}})
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>No hay libros en la biblioteca.</p>
  {% endif %}
{% endblock %}

Biblioteca/catalogo/templates/lista_libros_prestados.html
{% extends "base.html" %}

{% block contenido %}
    <h1>Libros en préstamo</h1>

    {% if libros %}
    <ul>

      {% for instancia in libros %}
      <li class="{% if instancia.esta_atrasado %}text-danger{% endif %}">
        <a href="{% url 'detalle-libro' instancia.libro.pk %}">{{ instancia.libro.titulo }}</a> ({{ instancia.fecha_entrega }}) pedido por {{ instancia.prestatario.username }} {% if perms.catalogo.puede_marcar_retornado %}- <a href="{% url 'renovar-libro-bibliotecario' instancia.pk %}">Renovar</a>{% endif %}
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>Actualmente no hay ningún libro en préstamo.</p>
    {% endif %}
{% endblock %}

Biblioteca/catalogo/templates/lista_libros_prestatario.html
{% extends "base.html" %}

{% block contenido %}
    <h1>Libros en préstamo para el usuario {{ user.username }}</h1>

    {% if libros %}
    <ul>

      {% for instancia in libros %}
      <li class="{% if instancia.esta_atrasado %}text-danger{% endif %}">
        <a href="{% url 'detalle-libro' instancia.libro.pk %}">{{ instancia.libro.titulo }}</a> ({{ instancia.fecha_entrega }})
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>No has pedido prestado ningún libro.</p>
    {% endif %}
{% endblock %}

Biblioteca/catalogo/templates/renovar_libro_bibliotecario.html
{% extends "base.html" %}

{% block contenido %}
  {% if formulario.errors %}
    <div class="alert alert-danger">
      {{ formulario.errors }}
    </div>
  {% endif %}
  <h1>Renueva: {{ instancia.libro.titulo }}</h1>
  <p>Prestatario: {{ instancia.prestatario }}</p>
  <p{% if instancia.esta_atrasado %} class="text-danger"{% endif %}> Due date: {{ instancia.fecha_entrega }}</p>

  <form action="" method="post">
    {% csrf_token %}
    <div class="form-group">
    {{ formulario.fecha_renovacion }}
      <button type="submit" class="btn btn-primary">Renovar</button>
    </div>
  </form>
{% endblock %}